[package]
name = "efecta"
version = "0.1.0"
authors = ["Alberto Elorza"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.clap]
git = "https://github.com/clap-rs/clap.git"